
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form" %>

<%
out.println("<!DOCTYPE html>");
out.println("<html lang=\"en\">");
out.println("<head>");
out.println("	<title>JavaWalla - Education Template</title>");
out.println("	<meta charset=\"UTF-8\">");
out.println("	<meta name=\"description\" content=\"WebUni Education Template\">");
out.println("	<meta name=\"keywords\" content=\"webuni, education, creative, html\">");
out.println("	<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">");
out.println("	<!-- Favicon -->   ");
out.println("	<link href=\"img/favicon.ico\" rel=\"shortcut icon\"/>");
out.println("");
out.println("	<!-- Google Fonts -->");
out.println("	<link href=\"https://fonts.googleapis.com/css?family=Raleway:400,400i,500,500i,600,600i,700,700i,800,800i\" rel=\"stylesheet\">");
out.println("");
out.println("	<!-- Stylesheets -->");
out.println("	<link rel=\"stylesheet\" href=\"css/bootstrap.min.css\"/>");
out.println("	<link rel=\"stylesheet\" href=\"css/font-awesome.min.css\"/>");
out.println("	<link rel=\"stylesheet\" href=\"css/owl.carousel.css\"/>");
out.println("	<link rel=\"stylesheet\" href=\"css/style.css\"/>");
out.println("");
out.println("");
out.println("	<!--[if lt IE 9]>");
out.println("	  <script src=\"https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js\"></script>");
out.println("	  <script src=\"https://oss.maxcdn.com/respond/1.4.2/respond.min.js\"></script>");
out.println("	<![endif]-->");
out.println("<script>");
out.println("");
out.println("	 window.onload=function(){");
out.println("	            const params = new URLSearchParams(window.location.search);");
out.println("                 var name= params.get('user');	");
out.println("                ");
out.println("");
out.println("                // var examlink= params.get('quiz');	");
out.println("//console.log(examlink);");
out.println("document.getElementById(\"am\").innerHTML = name;  ");
out.println("//document.getElementById(\"exam\").href = examlink; ");
out.println("");
out.println("var schoolList=\"${quiz}\";");
out.println("for(var i=0;i<schoolList.length;i++) {");
out.println("  alert(schoolList.length);");
out.println("}");
out.println("}");
out.println("");
out.println("</script>");
out.println("</head>");
out.println("<body>");
out.println("	<!-- Page Preloder -->");
out.println("	<div id=\"preloder\">");
out.println("		<div class=\"loader\"></div>");
out.println("	</div>");
out.println("");
out.println("	<!-- Header section -->");
out.println("	<header class=\"header-section\">");
out.println("		<div class=\"container\">");
out.println("			<div class=\"row\">");
out.println("				<div class=\"col-lg-3 col-md-3\">");
out.println("					<div class=\"site-logo\">");
out.println("						<img src=\"img/logo.png\" alt=\"\">");
out.println("					</div>");
out.println("					<div class=\"nav-switch\">");
out.println("						<i class=\"fa fa-bars\"></i>");
out.println("					</div>");
out.println("				</div>");
out.println("				<div class=\"col-lg-9 col-md-9\">");
out.println("					<a  class=\"site-btn header-btn\" id=\"am\">Sign/Sign Up</a>");
out.println("					<nav class=\"main-menu\">");
out.println("						<ul>");
out.println("							<li><a href=\"index.html\">Home</a></li>");
out.println("							<li><a href=\"#\">About us</a></li>");
out.println("							<li><a href=\"#cou\">Mock Test</a></li>");
out.println("							<li><a href=\"blog.html\">News</a></li>");
out.println("							<li><a href=\"#con\">Contact</a></li>");
out.println("							<li><a href=\"#jobs\">Jobs</a></li>");
out.println("						</ul>");
out.println("					</nav>");
out.println("				</div>");
out.println("			</div>");
out.println("		</div>");
out.println("	</header>");
out.println("	<!-- Header section end -->");
out.println("");
out.println("");
out.println("	<!-- Hero section -->");
out.println("	<section class=\"hero-section set-bg\" data-setbg=\"img/bg.jpg\">");
out.println("		<div class=\"container\">");
out.println("			<div class=\"hero-text text-white\">");
out.println("				<h2>Get The Best Free Online Mock Test</h2>");
out.println("				<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec malesuada lorem maximus mauris scelerisque, at rutrum nulla <br> dictum. Ut ac ligula sapien. Suspendisse cursus faucibus finibus.</p>");
out.println("			</div>");
out.println("			");
out.println("			<div class=\"row\">");
out.println("                <div class=\"column\" style=\"background-color:white;\">");
out.println("                     <h2 style=\"color:#dc3545\">Latest Quiz</h2>");
out.println("                     <!--<marquee direction=\"up\" style=\"color:#dc3545\">-->");
out.println("					 <a href=\"#\" id=\"exam\"><b>String mock test</b></a>");
out.println("					 ");
out.println("                </div>");
out.println("          <div class=\"column\" style=\"background-color:white;\">");
out.println("                   <h2 style=\"color:#dc3545\">Latest Jobs</h2>");
out.println("                  ");
out.println("				  <marquee>Latest String quiz</marquee>");
out.println("          </div>");
out.println("          </div>");
out.println("		</div>");
out.println("	</section>");
out.println("	<!-- Hero section end -->");
out.println("");
out.println("");
out.println("	<!-- categories section -->");
out.println("	<section class=\"categories-section spad\">");
out.println("		<div class=\"container\">");
out.println("			<div class=\"section-title\" id=\"jobs\">");
out.println("				<h2>Jobs For You</h2>");
out.println("				<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec malesuada lorem maximus mauris scelerisque, at rutrum nulla dictum. Ut ac ligula sapien. Suspendisse cursus faucibus finibus.</p>");
out.println("			</div>");
out.println("			<div class=\"row\" >");
out.println("				<!-- categorie -->");
out.println("				<div class=\"col-lg-4 col-md-6\">");
out.println("					<div class=\"categorie-item\">");
out.println("						<div class=\"ci-thumb set-bg\" data-setbg=\"img/categories/1.jpg\"></div>");
out.println("						<div class=\"ci-text\">");
out.println("							<h5>IT Development</h5>");
out.println("							<p>Lorem ipsum dolor sit amet, consectetur</p>");
out.println("							<span>120 Courses</span>");
out.println("						</div>");
out.println("					</div>");
out.println("				</div>");
out.println("				<!-- categorie -->");
out.println("				<div class=\"col-lg-4 col-md-6\">");
out.println("					<div class=\"categorie-item\">");
out.println("						<div class=\"ci-thumb set-bg\" data-setbg=\"img/categories/2.jpg\"></div>");
out.println("						<div class=\"ci-text\">");
out.println("							<h5>Web Design</h5>");
out.println("							<p>Lorem ipsum dolor sit amet, consectetur</p>");
out.println("							<span>70 Courses</span>");
out.println("						</div>");
out.println("					</div>");
out.println("				</div>");
out.println("				<!-- categorie -->");
out.println("				<div class=\"col-lg-4 col-md-6\">");
out.println("					<div class=\"categorie-item\">");
out.println("						<div class=\"ci-thumb set-bg\" data-setbg=\"img/categories/3.jpg\"></div>");
out.println("						<div class=\"ci-text\">");
out.println("							<h5>Illustration & Drawing</h5>");
out.println("							<p>Lorem ipsum dolor sit amet, consectetur</p>");
out.println("							<span>55 Courses</span>");
out.println("						</div>");
out.println("					</div>");
out.println("				</div>");
out.println("				<!-- categorie -->");
out.println("				<div class=\"col-lg-4 col-md-6\">");
out.println("					<div class=\"categorie-item\">");
out.println("						<div class=\"ci-thumb set-bg\" data-setbg=\"img/categories/4.jpg\"></div>");
out.println("						<div class=\"ci-text\">");
out.println("							<h5>Social Media</h5>");
out.println("							<p>Lorem ipsum dolor sit amet, consectetur</p>");
out.println("							<span>40 Courses</span>");
out.println("						</div>");
out.println("					</div>");
out.println("				</div>");
out.println("				<!-- categorie -->");
out.println("				<div class=\"col-lg-4 col-md-6\">");
out.println("					<div class=\"categorie-item\">");
out.println("						<div class=\"ci-thumb set-bg\" data-setbg=\"img/categories/5.jpg\"></div>");
out.println("						<div class=\"ci-text\">");
out.println("							<h5>Photoshop</h5>");
out.println("							<p>Lorem ipsum dolor sit amet, consectetur</p>");
out.println("							<span>220 Courses</span>");
out.println("						</div>");
out.println("					</div>");
out.println("				</div>");
out.println("				<!-- categorie -->");
out.println("				<div class=\"col-lg-4 col-md-6\">");
out.println("					<div class=\"categorie-item\">");
out.println("						<div class=\"ci-thumb set-bg\" data-setbg=\"img/categories/6.jpg\"></div>");
out.println("						<div class=\"ci-text\">");
out.println("							<h5>Cryptocurrencies</h5>");
out.println("							<p>Lorem ipsum dolor sit amet, consectetur</p>");
out.println("							<span>25 Courses</span>");
out.println("						</div>");
out.println("					</div>");
out.println("				</div>");
out.println("			</div>");
out.println("		</div>");
out.println("	</section>");
out.println("	<!-- categories section end -->");
out.println("");
out.println("");
out.println("	<!-- search section -->");
out.println("	<section class=\"search-section\">");
out.println("		<div class=\"container\">");
out.println("			<div class=\"search-warp\">");
out.println("				<div class=\"section-title text-white\">");
out.println("					<h2>Search your course</h2>");
out.println("				</div>");
out.println("				<div class=\"row\">");
out.println("					<div class=\"col-md-10 offset-md-1\">");
out.println("						<!-- search form -->");
out.println("						<form class=\"course-search-form\">");
out.println("							<input type=\"text\" placeholder=\"Course\">");
out.println("							<input type=\"text\" class=\"last-m\" placeholder=\"Category\">");
out.println("							<button class=\"site-btn\">Search Couse</button>");
out.println("						</form>");
out.println("					</div>");
out.println("				</div>");
out.println("			</div>");
out.println("		</div>");
out.println("	</section>");
out.println("	<!-- search section end -->");
out.println("");
out.println("");
out.println("	<!-- course section -->");
out.println("	<section class=\"course-section spad\">");
out.println("		<div class=\"container\">");
out.println("			<div class=\"section-title mb-0\">");
out.println("				<h2>Featured Courses</h2>");
out.println("				<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec malesuada lorem maximus mauris scelerisque, at rutrum nulla dictum. Ut ac ligula sapien. Suspendisse cursus faucibus finibus.</p>");
out.println("			</div>");
out.println("		</div>");
out.println("		<div class=\"course-warp\" id=\"cou\">");
out.println("			<ul class=\"course-filter controls\">");
out.println("				<li class=\"control active\" data-filter=\"all\">All</li>");
out.println("				<li class=\"control\" data-filter=\".finance\">Spring Framework</li>");
out.println("				<li class=\"control\" data-filter=\".design\">Database</li>");
out.println("				<li class=\"control\" data-filter=\".web\">Web Development</li>");
out.println("				<li class=\"control\" data-filter=\".photo\">Java</li>");
out.println("			</ul>                                       ");
out.println("			<div class=\"row course-items-area\">");
out.println("				<!-- course -->");
out.println("				<div class=\"mix col-lg-3 col-md-4 col-sm-6 finance\">");
out.println("					<div class=\"course-item\">");
out.println("						<div class=\"course-thumb set-bg\" data-setbg=\"img/courses/1.jpg\">");
out.println("							");
out.println("						</div>");
out.println("						<div class=\"course-info\">");
out.println("							<div class=\"course-text\">");
out.println("								<h5>Spring MVC</h5>");
out.println("								<p>Lorem ipsum dolor sit amet, consectetur</p>");
out.println("								<div class=\"students\">120 Students</div>");
out.println("							</div>");
out.println("						");
out.println("						</div>");
out.println("					</div>");
out.println("				</div>");
out.println("				<!-- course -->");
out.println("				<div class=\"mix col-lg-3 col-md-4 col-sm-6 design\">");
out.println("					<div class=\"course-item\">");
out.println("						<div class=\"course-thumb set-bg\" data-setbg=\"img/courses/2.jpg\">");
out.println("							");
out.println("						</div>");
out.println("						<div class=\"course-info\">");
out.println("							<div class=\"course-text\">");
out.println("								<h5>SQL</h5>");
out.println("								<p>Lorem ipsum dolor sit amet, consectetur</p>");
out.println("								<div class=\"students\">120 Students</div>");
out.println("							</div>");
out.println("							");
out.println("						</div>");
out.println("					</div>");
out.println("				</div>");
out.println("				<!-- course -->");
out.println("				<div class=\"mix col-lg-3 col-md-4 col-sm-6 web\">");
out.println("					<div class=\"course-item\">");
out.println("						<div class=\"course-thumb set-bg\" data-setbg=\"img/courses/3.jpg\">");
out.println("							");
out.println("						</div>");
out.println("						<div class=\"course-info\">");
out.println("							<div class=\"course-text\">");
out.println("								<h5>HTML</h5>");
out.println("								<p>Lorem ipsum dolor sit amet, consectetur</p>");
out.println("								<div class=\"students\">120 Students</div>");
out.println("							</div>");
out.println("							");
out.println("						</div>");
out.println("					</div>");
out.println("				</div>");
out.println("				<!-- course -->");
out.println("				<div class=\"mix col-lg-3 col-md-4 col-sm-6 photo\">");
out.println("					<div class=\"course-item\">");
out.println("						<div class=\"course-thumb set-bg\" data-setbg=\"img/courses/4.jpg\">");
out.println("							");
out.println("						</div>");
out.println("						<div class=\"course-info\">");
out.println("							<div class=\"course-text\">");
out.println("								<h5>Collection</h5>");
out.println("								<p>Lorem ipsum dolor sit amet, consectetur</p>");
out.println("								<div class=\"students\">120 Students</div>");
out.println("							</div>");
out.println("							");
out.println("						</div>");
out.println("					</div>");
out.println("				</div>");
out.println("					<div class=\"mix col-lg-3 col-md-4 col-sm-6 photo\">");
out.println("					<div class=\"course-item\">");
out.println("						<div class=\"course-thumb set-bg\" data-setbg=\"img/courses/4.jpg\">");
out.println("							");
out.println("						</div>");
out.println("						<div class=\"course-info\">");
out.println("							<div class=\"course-text\">");
out.println("								<h5>MultiThreading</h5>");
out.println("								<p>Lorem ipsum dolor sit amet, consectetur</p>");
out.println("								<div class=\"students\">120 Students</div>");
out.println("							</div>");
out.println("							");
out.println("						</div>");
out.println("					</div>");
out.println("				</div>");
out.println("					<div class=\"mix col-lg-3 col-md-4 col-sm-6 photo\">");
out.println("					<div class=\"course-item\">");
out.println("						<div class=\"course-thumb set-bg\" data-setbg=\"img/courses/4.jpg\">");
out.println("							");
out.println("						</div>");
out.println("						<div class=\"course-info\">");
out.println("							<div class=\"course-text\">");
out.println("								<h5>Exception Handling</h5>");
out.println("								<p>Lorem ipsum dolor sit amet, consectetur</p>");
out.println("								<div class=\"students\">120 Students</div>");
out.println("							</div>");
out.println("							");
out.println("						</div>");
out.println("					</div>");
out.println("				</div>");
out.println("				<!-- course -->");
out.println("				<div class=\"mix col-lg-3 col-md-4 col-sm-6 finance\">");
out.println("					<div class=\"course-item\">");
out.println("						<div class=\"course-thumb set-bg\" data-setbg=\"img/courses/5.jpg\">");
out.println("						");
out.println("						</div>");
out.println("						<div class=\"course-info\">");
out.println("							<div class=\"course-text\">");
out.println("								<h5>Spring Boot</h5>");
out.println("								<p>Lorem ipsum dolor sit amet, consectetur</p>");
out.println("								<div class=\"students\">120 Students</div>");
out.println("							</div>");
out.println("						");
out.println("						</div>");
out.println("					</div>");
out.println("				</div>");
out.println("				<!-- course -->");
out.println("				<div class=\"mix col-lg-3 col-md-4 col-sm-6 design\">");
out.println("					<div class=\"course-item\">");
out.println("						<div class=\"course-thumb set-bg\" data-setbg=\"img/courses/6.jpg\">");
out.println("							");
out.println("						</div>");
out.println("						<div class=\"course-info\">");
out.println("							<div class=\"course-text\">");
out.println("								<h5>MYSQL</h5>");
out.println("								<p>Lorem ipsum dolor sit amet, consectetur</p>");
out.println("								<div class=\"students\">120 Students</div>");
out.println("							</div>");
out.println("							");
out.println("						</div>");
out.println("					</div>");
out.println("				</div>");
out.println("				<!-- course -->");
out.println("				<div class=\"mix col-lg-3 col-md-4 col-sm-6 web\">");
out.println("					<div class=\"course-item\">");
out.println("						<div class=\"course-thumb set-bg\" data-setbg=\"img/courses/7.jpg\">");
out.println("							");
out.println("						</div>");
out.println("						<div class=\"course-info\">");
out.println("							<div class=\"course-text\">");
out.println("								<h5>Javascript</h5>");
out.println("								<p>Lorem ipsum dolor sit amet, consectetur</p>");
out.println("								<div class=\"students\">120 Students</div>");
out.println("							</div>");
out.println("						");
out.println("						</div>");
out.println("					</div>");
out.println("				</div>");
out.println("				<!-- course -->");
out.println("				<div class=\"mix col-lg-3 col-md-4 col-sm-6 photo\">");
out.println("					<div class=\"course-item\">");
out.println("						<div class=\"course-thumb set-bg\" data-setbg=\"img/courses/8.jpg\">");
out.println("							");
out.println("						</div>");
out.println("						<div class=\"course-info\">");
out.println("							<div class=\"course-text\">");
out.println("								<h5>String</h5>");
out.println("								<p>Lorem ipsum dolor sit amet, consectetur</p>");
out.println("								<div class=\"students\">120 Students</div>");
out.println("							</div>");
out.println("							");
out.println("						</div>");
out.println("					</div>");
out.println("				</div>");
out.println("			</div>");
out.println("		</div>");
out.println("	</section>");
out.println("	<!-- course section end -->");
out.println("");
out.println("");
out.println("	<!-- signup section ");
out.println("	<section class=\"signup-section spad\">");
out.println("		<div class=\"signup-bg set-bg\" data-setbg=\"img/signup-bg.jpg\"></div>");
out.println("		<div class=\"container-fluid\">");
out.println("			<div class=\"row\">");
out.println("				<div class=\"col-lg-6\">");
out.println("					<div class=\"signup-warp\">");
out.println("						<div class=\"section-title text-white text-left\">");
out.println("							<h2>Sign up to became a teacher</h2>");
out.println("							<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec malesuada lorem maximus mauris scelerisque, at rutrum nulla dictum. Ut ac ligula sapien. Suspendisse cursus faucibus finibus.</p>");
out.println("						</div>");
out.println("						<!-- signup form ");
out.println("						<form class=\"signup-form\">");
out.println("							<input type=\"text\" placeholder=\"Your Name\">");
out.println("							<input type=\"text\" placeholder=\"Your E-mail\">");
out.println("							<input type=\"text\" placeholder=\"Your Phone\">");
out.println("							<label for=\"v-upload\" class=\"file-up-btn\">Upload Course</label>");
out.println("							<input type=\"file\" id=\"v-upload\">");
out.println("							<button class=\"site-btn\">Search Couse</button>");
out.println("						</form>");
out.println("					</div>");
out.println("				</div>");
out.println("			</div>");
out.println("		</div>");
out.println("	</section> -->");
out.println("	<!-- signup section end -->");
out.println("");
out.println("");
out.println("	<!-- banner section ");
out.println("	<section class=\"banner-section spad\">");
out.println("		<div class=\"container\">");
out.println("			<div class=\"section-title mb-0 pb-2\">");
out.println("				<h2>Join Our Community Now!</h2>");
out.println("				<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec malesuada lorem maximus mauris scelerisque, at rutrum nulla dictum. Ut ac ligula sapien. Suspendisse cursus faucibus finibus.</p>");
out.println("			</div>");
out.println("			<div class=\"text-center pt-5\">");
out.println("				<a href=\"#\" class=\"site-btn\">Register Now</a>");
out.println("			</div>");
out.println("		</div>");
out.println("	</section>");
out.println("	banner section end    -->");
out.println("<section class=\"contact-page spad pb-0\" id=\"con\">");
out.println("		<div class=\"container\">");
out.println("			<div class=\"row\">");
out.println("				<div class=\"col-lg-8\">");
out.println("					<div class=\"contact-form-warp\">");
out.println("						<div class=\"section-title text-white text-left\">");
out.println("							<h2>Get in Touch</h2>");
out.println("							<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec malesuada lorem maximus mauris scelerisque, at rutrum nulla dictum. Ut ac ligula sapien. </p>");
out.println("						</div>");
out.println("						<form class=\"contact-form\">");
out.println("							<input type=\"text\" placeholder=\"Your Name\">");
out.println("							<input type=\"text\" placeholder=\"Your E-mail\">");
out.println("							<input type=\"text\" placeholder=\"Subject\">");
out.println("							<textarea placeholder=\"Message\"></textarea>");
out.println("							<button class=\"site-btn\">Sent Message</button>");
out.println("						</form>");
out.println("					</div>");
out.println("				</div>");
out.println("				<div class=\"col-lg-4\">");
out.println("					<div class=\"contact-info-area\">");
out.println("						<div class=\"section-title text-left p-0\">");
out.println("							<h2>Contact Info</h2>");
out.println("							<p>Donec malesuada lorem maximus mauris scelerisque, at rutrum nulla dictum. Ut ac ligula sapien. Suspendi sse cursus faucibus finibus.</p>");
out.println("						</div>");
out.println("						<div class=\"phone-number\">");
out.println("							<span>Direct Line</span>");
out.println("							<h2>+53 345 7953 32453</h2>");
out.println("						</div>");
out.println("						<ul class=\"contact-list\">");
out.println("							<li>1481 Creekside Lane <br>Avila Beach, CA 931</li>");
out.println("							<li>+53 345 7953 32453</li>");
out.println("							<li>yourmail@gmail.com</li>");
out.println("						</ul>");
out.println("						<div class=\"social-links\">");
out.println("							<a href=\"#\"><i class=\"fa fa-pinterest\"></i></a>");
out.println("							<a href=\"#\"><i class=\"fa fa-facebook\"></i></a>");
out.println("							<a href=\"#\"><i class=\"fa fa-twitter\"></i></a>");
out.println("							<a href=\"#\"><i class=\"fa fa-dribbble\"></i></a>");
out.println("							<a href=\"#\"><i class=\"fa fa-behance\"></i></a>");
out.println("							<a href=\"#\"><i class=\"fa fa-linkedin\"></i></a>");
out.println("						</div>");
out.println("					</div>");
out.println("				</div>");
out.println("			</div>");
out.println("			");
out.println("		</div>");
out.println("	</section> ");
out.println("");
out.println("	<!-- footer section -->");
out.println("	<footer class=\"footer-section spad pb-0\">");
out.println("		<div class=\"footer-top\">");
out.println("			<div class=\"footer-warp\">");
out.println("				<div class=\"row\">");
out.println("					<div class=\"widget-item\">");
out.println("						<h4>Contact Info</h4>");
out.println("						<ul class=\"contact-list\">");
out.println("							<li>1481 Creekside Lane <br>Avila Beach, CA 931</li>");
out.println("							<li>+53 345 7953 32453</li>");
out.println("							<li>yourmail@gmail.com</li>");
out.println("						</ul>");
out.println("					</div>");
out.println("					<div class=\"widget-item\">");
out.println("						<h4>Engeneering</h4>");
out.println("						<ul>");
out.println("							<li><a href=\"\">Applied Studies</a></li>");
out.println("							<li><a href=\"\">Computer Engeneering</a></li>");
out.println("							<li><a href=\"\">Software Engeneering</a></li>");
out.println("							<li><a href=\"\">Informational Engeneering</a></li>");
out.println("							<li><a href=\"\">System Engeneering</a></li>");
out.println("						</ul>");
out.println("					</div>");
out.println("					<div class=\"widget-item\">");
out.println("						<h4>Graphic Design</h4>");
out.println("						<ul>");
out.println("							<li><a href=\"\">Applied Studies</a></li>");
out.println("							<li><a href=\"\">Computer Engeneering</a></li>");
out.println("							<li><a href=\"\">Software Engeneering</a></li>");
out.println("							<li><a href=\"\">Informational Engeneering</a></li>");
out.println("							<li><a href=\"\">System Engeneering</a></li>");
out.println("						</ul>");
out.println("					</div>");
out.println("					<div class=\"widget-item\">");
out.println("						<h4>Development</h4>");
out.println("						<ul>");
out.println("							<li><a href=\"\">Applied Studies</a></li>");
out.println("							<li><a href=\"\">Computer Engeneering</a></li>");
out.println("							<li><a href=\"\">Software Engeneering</a></li>");
out.println("							<li><a href=\"\">Informational Engeneering</a></li>");
out.println("							<li><a href=\"\">System Engeneering</a></li>");
out.println("						</ul>");
out.println("					</div>");
out.println("					<div class=\"widget-item\">");
out.println("						<h4>Newsletter</h4>");
out.println("						<form class=\"footer-newslatter\">");
out.println("							<input type=\"email\" placeholder=\"E-mail\">");
out.println("							<button class=\"site-btn\">Subscribe</button>");
out.println("							<p>*We don’t spam</p>");
out.println("						</form>");
out.println("					</div>");
out.println("				</div>");
out.println("			</div>");
out.println("		</div>");
out.println("		<div class=\"footer-bottom\">");
out.println("			<div class=\"footer-warp\">");
out.println("				<ul class=\"footer-menu\">");
out.println("					<li><a href=\"#\">Terms & Conditions</a></li>");
out.println("					<li><a href=\"#\">Register</a></li>");
out.println("					<li><a href=\"#\">Privacy</a></li>");
out.println("				</ul>");
out.println("				<div class=\"copyright\"><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->");
out.println("Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class=\"fa fa-heart-o\" aria-hidden=\"true\"></i> by <a href=\"https://colorlib.com\" target=\"_blank\">Colorlib</a>");
out.println("<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></div>");
out.println("			</div>");
out.println("		</div>");
out.println("	</footer> ");
out.println("	<!-- footer section end -->");
out.println("");
out.println("");
out.println("	<!--====== Javascripts & Jquery ======-->");
out.println("	<script src=\"js/jquery-3.2.1.min.js\"></script>");
out.println("	<script src=\"js/bootstrap.min.js\"></script>");
out.println("	<script src=\"js/mixitup.min.js\"></script>");
out.println("	<script src=\"js/circle-progress.min.js\"></script>");
out.println("	<script src=\"js/owl.carousel.min.js\"></script>");
out.println("	<script src=\"js/main.js\"></script>");
out.println("	<style>");
out.println("	.column {");
out.println("  float: center;");
out.println("  margin: auto;");
out.println("  width: 40%;");
out.println("  padding: 20px;");
out.println("  height: 200px; /* Should be removed. Only for demonstration */");
out.println("}");
out.println("");
out.println("/* Clear floats after the columns */");
out.println(".row:after {");
out.println("  content: \"\";");
out.println("  display: table;");
out.println("  margin: auto;");
out.println("  clear: both;");
out.println("}</style>");
out.println("</html>");
%>